### /produto (get): retorna uma lista de produtos ativos
GET http://localhost:3000/produto

### /produto (post): adiciona um novo produto e retorna o mesmo
POST http://localhost:3000/produto
Content-Type: application/json

{
    "nome": "Abacaxi",
    "descricao": "Abacaxi excepcional jamais visto"
}

### /produto/:id (get): retorna um produto buscando pelo id do mesmo, juntamente com os seus dados de operação, dentro do campo "operacoes"
GET http://localhost:3000/produto/1