### /produto (get): retorna uma lista de produtos ativos
GET http://localhost:3000/produto

### /produto (post): adiciona um novo produto e retorna o mesmo
POST http://localhost:3000/produto
Content-Type: application/json

{
    "nome": "Abacaxi",
    "descricao": "Abacaxi excepcional jamais visto"
}

### /produto/:id (get): retorna um produto buscando pelo id do mesmo, juntamente com os seus dados de operação, dentro do campo "operacoes"
GET http://localhost:3000/produto/4

### /produto/:id (patch): atualiza um produto buscando pelo id do mesmo, retornando os dados do produto atualizado
PATCH http://localhost:3000/produto/4
Content-Type: application/json

{
    "quantidade": 120,
    "status": true
}

### /produto/:id (delete): desativa um produto, ou seja, atualiza o status do mesmo para false e retorna seus dados atualizados
DELETE http://localhost:3000/produto/4

### /produto/:id/comprar (post): realiza uma operação de compra do produto, atualizando o preço e quantidade, retornando os dados da operação, com os dados do produto da operação realizada
POST http://localhost:3000/produto/4/comprar
Content-Type: application/json

{
    "quantidade": 10,
    "preco": 12
}

### /produto/:id/vender (post): realiza uma operação de venda do produto, atualizando a quantidade, retornando os dados da operação, com os dados do produto da operação realizada
POST http://localhost:3000/produto/4/vender
Content-Type: application/json

{
    "quantidade": 10,
    "preco": 12
}